#!/usr/bin/env bash
set -euo pipefail
# create_sparkhugo.sh
# Creates minimal project files for sparkhugo if they don't exist.
echo "Creating/refreshing sparkhugo structure..."
mkdir -p assets/css layouts/_default layouts/partials content/posts static/css .github/workflows

# Tailwind entry
cat > assets/css/tailwind.css <<'EOF'
@tailwind base;
@tailwind components;
@tailwind utilities;
EOF

# Sample layout partial (head)
mkdir -p layouts/partials
cat > layouts/partials/head.html <<'EOF'
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{{ if .IsHome }}{{ .Site.Title }}{{ else }}{{ .Title }} - {{ .Site.Title }}{{ end }}</title>
<link rel="stylesheet" href="/css/styles.css">
EOF

# Base template
cat > layouts/_default/baseof.html <<'EOF'
<!doctype html>
<html lang="en">
<head>
  {{ partial "head.html" . }}
</head>
<body class="min-h-screen antialiased font-sans bg-gray-50 text-gray-900">
  <header class="bg-white shadow-sm">
    <div class="max-w-4xl mx-auto p-4">
      <h1 class="text-2xl font-bold"><a href="{{ .Site.BaseURL }}">{{ .Site.Title }}</a></h1>
    </div>
  </header>
  <main class="max-w-4xl mx-auto p-6">
    {{ block "main" . }}{{ end }}
  </main>
  <footer class="max-w-4xl mx-auto p-6 text-sm text-gray-500">
    Built with Hugo + Tailwind
  </footer>
</body>
</html>
EOF

# Index template
cat > layouts/index.html <<'EOF'
{{ define "main" }}
<section>
  <h2 class="text-xl font-semibold mb-4">Welcome to {{ .Site.Title }}</h2>
  {{ if .Site.Home.Params.description }}<p class="mb-6">{{ .Site.Home.Params.description }}</p>{{ end }}
  <ul class="space-y-4">
    {{ range .Pages }}
    <li class="border rounded p-4 bg-white"><a href="{{ .RelPermalink }}" class="text-lg font-medium">{{ .Title }}</a><p class="text-sm text-gray-600">{{ .Summary }}</p></li>
    {{ end }}
  </ul>
</section>
{{ end }}
EOF

# Single page template
cat > layouts/_default/single.html <<'EOF'
{{ define "main" }}
<article class="prose lg:prose-xl">
  <h1>{{ .Title }}</h1>
  <div>{{ .Content }}</div>
</article>
{{ end }}
EOF

# Content
mkdir -p content/posts
cat > content/_index.md <<'EOF'
+++
title = "SparkHugo demo"
description = "A tiny Hugo + Tailwind demo site generated by a script."
+++

Welcome to the SparkHugo demo site.
EOF

cat > content/posts/hello-world.md <<'EOF'
+++
title = "Hello, SparkHugo!"
date = "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
+++

This is the first post. Edit or replace it.
EOF

# Config
cat > config.toml <<'EOF'
baseURL = "https://yoloinfinity55.github.io/"
languageCode = "en-us"
title = "sparkhugo"
theme = ""
publishDir = "public"
EOF

# package.json (dev deps only)
cat > package.json <<'EOF'
{
  "name": "sparkhugo",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "build:css": "npx tailwindcss -i ./assets/css/tailwind.css -o ./static/css/styles.css --minify",
    "build": "npm run build:css && hugo --minify"
  },
  "devDependencies": {
    "tailwindcss": "^3.0.0",
    "postcss": "^8.0.0",
    "autoprefixer": "^10.0.0"
  }
}
EOF

# Tailwind & postcss config
cat > tailwind.config.js <<'EOF'
module.exports = {
  content: [
    "./layouts/**/*.html",
    "./content/**/*.md",
    "./assets/**/*.css"
  ],
  theme: { extend: {} },
  plugins: [],
}
EOF

cat > postcss.config.js <<'EOF'
module.exports = {
  plugins: {
    autoprefixer: {},
  }
}
EOF

# .gitignore
cat > .gitignore <<'EOF'
/public/
/node_modules/
.DS_Store
EOF

chmod +x create_sparkhugo.sh
echo "Done. Run 'npm install' then 'npm run build' or use build.sh."
